on:
  schedule:
    - cron: "0 * * * *"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Run our action
        id: step1-id
        uses: 0x4448/hello-github-action@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arg-name1: "0x4448"

      - name: Print the output
        run: echo "The output is ${{ steps.step1-id.outputs.out-var1 }}"
